DATA CERTSDCEDAR21;
LENGTH SDTRT $ 18; 
INFILE 'C:\' FIRSTOBS=4;
INPUT LOC $ PLOT REP TRT VARIETY $ SDTRT $ SDRATE FLOWER WEIGHT MOIST TEST PROT PLTSIZE;
YLD=(WEIGHT)*(100-MOIST)/87;
YIELD=(YLD/454)*(43560/PLTSIZE);      ** YIELD LB/AC **;
YIELD=YIELD/60;                       ** YIELD BU/AC **;
PROC SORT; BY LOC REP SDTRT SDRATE;
/*PROC PRINT DATA=CERTSDCEDAR21;
RUN;
PROC UNIVARIATE DATA=CERTSDCEDAR21 NORMAL PLOT; BY LOC;
VAR YIELD TEST PROT;
RUN;*/

PROC GLM; BY LOC;
CLASS REP SDTRT SDRATE;
MODEL YIELD TEST PROT=SDTRT REP(SDTRT) SDRATE SDTRT*SDRATE/SS3;
TEST H=SDTRT E=REP(SDTRT);
MEANS SDTRT SDRATE/LSD;
LSMEANS SDTRT SDRATE SDTRT*SDRATE/OUT=MEANSSDTRT;
PROC PRINT DATA=MEANSSDTRT;
RUN;*/

** COMBINED ANALYSIS *;
PROC GLM; 
CLASS LOC REP SDTRT SDRATE;
MODEL YIELD TEST PROT=LOC REP(LOC) SDTRT LOC*SDTRT REP(LOC*SDTRT) SDRATE  LOC*SDRATE LOC*SDTRT*SDRATE/SS3;
TEST H=LOC E=REP(LOC);
TEST H=SDTRT E=REP(LOC*SDTRT);
TEST H=LOC*SDTRT E=REP(LOC*SDTRT);
MEANS LOC SDTRT SDRATE/LSD;
LSMEANS LOC SDTRT SDRATE LOC*SDTRT LOC*SDRATE LOC*SDTRT*SDRATE/OUT=CMEANSSDTRT;
PROC PRINT DATA=CMEANSSDTRT;
RUN;
