OPTIONS LINESIZE=80 PAGESIZE=60 NODATE;
DATA DATAGEM2021;
LENGTH VNAME $ 20; 
INFILE 'C:\' FIRSTOBS=3;
INPUT LOC $ PLOT REP PURPOSE $ VNAME $ SDRATE NRATE DM HEADING WGT MOIST TEST TKW PROT PLOTL PLOTW SORTN;
/*DROP SORTN;*/
YLD=(WGT)*(100-MOIST)/87;
YIELD=(YLD/454)*(43560/(PLOTL*PLOTW));       ** YIELD LB/AC **;
YIELD=YIELD/60;                               ** YIELD BU/AC **;
PROC SORT; BY LOC REP PURPOSE VNAME SDRATE NRATE;
RUN;
/*PROC PRINT DATA=DATAGEM2021;
RUN;
PROC UNIVARIATE DATA=DATAGEM2021 NORMAL PLOT; BY LOC;
VAR DM HEADING YIELD TEST TKW PROT;
RUN;*/

** ANALYSES AT EACH LOCATION - GEI 2021**;

PROC GLM DATA=DATAGEM2021; BY LOC;
CLASS LOC REP PURPOSE VNAME SDRATE NRATE;
MODEL HEADING YIELD PROT TEST TKW =REP PURPOSE REP*PURPOSE VNAME PURPOSE*VNAME REP*PURPOSE*VNAME
                                   SDRATE*NRATE PURPOSE*SDRATE*NRATE VNAME*SDRATE*NRATE PURPOSE*VNAME*SDRATE*NRATE/SS3;
TEST H=PURPOSE E=REP*PURPOSE;
TEST H=VNAME E=REP*PURPOSE*VNAME;
TEST H=PURPOSE*VNAME E=REP*PURPOSE*VNAME;
MEANS PURPOSE VNAME PURPOSE*VNAME SDRATE*NRATE PURPOSE*SDRATE*NRATE VNAME*SDRATE*NRATE PURPOSE*VNAME*SDRATE*NRATE/LSD LINES;
LSMEANS PURPOSE VNAME PURPOSE*VNAME SDRATE*NRATE PURPOSE*SDRATE*NRATE VNAME*SDRATE*NRATE PURPOSE*VNAME*SDRATE*NRATE/OUT=MEANSGEM21;
PROC PRINT DATA=MEANSGEM21;
TITLE "GEM 2021 ANOVA PER LOCATION";
RUN;*/

** ANALYSES WITHIN DUAL PURPOSE AT EACH LOCATION - GEI 2021**;
DATA DATADUAL2021;
SET DATAGEM2021;
IF PURPOSE="Grain" THEN DELETE;
PROC SORT; BY LOC REP PURPOSE VNAME SDRATE NRATE;
RUN;
/*PROC PRINT DATA=DATADUAL2021;
RUN;*/
PROC GLM DATA=DATADUAL2021; BY LOC;
CLASS LOC REP VNAME SDRATE NRATE;
MODEL DM HEADING YIELD TEST TKW PROT =REP VNAME REP*VNAME SDRATE*NRATE VNAME*SDRATE*NRATE /SS3;
TEST H=VNAME E=REP*VNAME;
MEANS VNAME SDRATE*NRATE VNAME*SDRATE*NRATE/LSD LINES;
LSMEANS VNAME SDRATE*NRATE VNAME*SDRATE*NRATE/OUT=MEANSDGEM21;
PROC PRINT DATA=MEANSDGEM21;
TITLE "GEM 2021 ANOVA PER LOCATION";
RUN;


/** COMBINED ANALYSES ACROSS LOCATIONS -ST 2021 **;
PROC GLM DATA=ST21;
CLASS LOC REP ENAME;
MODEL YIELD TEST=LOC REP(LOC) ENAME LOC*ENAME/SS3;
MEANS ENAME/LSD LINES;
LSMEANS ENAME/OUT=MEANSSTC21;
PROC PRINT DATA=MEANSSTC21;
TITLE "ST 2021 COMBINED ANOVA ACROSS LOCATIONS";
RUN;
