DATA ZNSTUDY21;
LENGTH VARIETY $ 20; 
INFILE 'C:\' FIRSTOBS=4;
INPUT LOC $ PLOT REP ZNTRT $ VARIETY $  FLOWER WEIGHT MOIST TEST PROT TKW PLTSIZE ZN FE MG MN CU P;
IF LOC="CS" AND PLOT=121 THEN WEIGHT="."; IF LOC="CS" AND PLOT=147 THEN WEIGHT="."; IF LOC="CS" AND PLOT=150 THEN WEIGHT=".";
IF LOC="CS" AND PLOT=159 THEN WEIGHT="."; IF LOC="CS" AND PLOT=168 THEN WEIGHT="."; IF LOC="CS" AND PLOT=170 THEN WEIGHT="."; 
IF LOC="CS" AND PLOT=179 THEN WEIGHT=".";
YLD=(WEIGHT)*(100-MOIST)/87;
YIELD=(YLD/454)*(43560/PLTSIZE);      ** YIELD LB/AC **;
YIELD=YIELD/60;                       ** YIELD BU/AC **;
PROC SORT; BY LOC REP ZNTRT VARIETY;
/*PROC PRINT DATA=ZNSTUDY21;
RUN;
PROC UNIVARIATE DATA=ZNSTUDY21 NORMAL PLOT; BY LOC;
VAR FLOWER YIELD TEST PROT TKW ZN FE MG MN CU P;
RUN;*/

PROC GLM; BY LOC;
CLASS REP ZNTRT VARIETY;
MODEL FLOWER YIELD TEST PROT TKW ZN FE MG MN CU P=ZNTRT REP(ZNTRT) VARIETY ZNTRT*VARIETY/SS3;
TEST H=ZNTRT E=REP(ZNTRT);
MEANS ZNTRT VARIETY/LSD;
LSMEANS ZNTRT VARIETY ZNTRT*VARIETY/OUT=MEANSZN;
PROC PRINT DATA=MEANSZN;
RUN;*/

** COMBINED ANALYSIS *;
PROC GLM; 
CLASS LOC REP ZNTRT VARIETY;
MODEL FLOWER YIELD TEST PROT TKW=LOC REP(LOC) ZNTRT LOC*ZNTRT REP(LOC*ZNTRT) VARIETY LOC*VARIETY ZNTRT*VARIETY LOC*ZNTRT*VARIETY/SS3;
TEST H=LOC E=REP(LOC);
TEST H=ZNTRT E=REP(LOC*ZNTRT);
TEST H=LOC*ZNTRT E=REP(LOC*ZNTRT);
MEANS LOC ZNTRT VARIETY/LSD;
LSMEANS LOC ZNTRT VARIETY LOC*ZNTRT LOC*VARIETY ZNTRT*VARIETY LOC*ZNTRT*VARIETY/OUT=CMEANSZN;
PROC PRINT DATA=CMEANSZN;
RUN;
